INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Batchwood / Bernards Heath');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Bricket Wood');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Brookmans Park');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Cell Barnes & Camp');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Colney Heath');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Harpenden');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Hatfield');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Hatfield Road');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Heartwood Forest');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Highfield & Tyttenhanger');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Jersey Farm');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'London Colney');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Marshalswick');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'New Greens');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Nomansland');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Oaklands / Hatfield Road');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Other');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Park Street');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Redbourn');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Sandridge');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Sopwell');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Town Center');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Verulamium & Cathedral');
INSERT INTO areas (id, name) VALUES (nextval('hibernate_sequence'),'Wheathampstead');