CREATE SEQUENCE gymids;
BEGIN;
SET CONSTRAINTS ALL DEFERRED;
ALTER TABLE gyms DISABLE TRIGGER USER;
ALTER TABLE user_gym_props DISABLE TRIGGER USER;
ALTER TABLE comments DISABLE TRIGGER USER;
UPDATE gyms SET id=id+1000;
UPDATE user_gym_props SET gymid=gymid+1000;
UPDATE comments SET gymid=gymid+1000;
CREATE TABLE gym_mapping(oldid, newid) AS (SELECT id, nextval('gymids') FROM gyms ORDER BY name);
UPDATE gyms SET id=(SELECT newid FROM gym_mapping WHERE oldid=gyms.id);
UPDATE user_gym_props SET gymid=(SELECT newid FROM gym_mapping WHERE oldid=user_gym_props.gymid);
UPDATE comments SET gymid=(SELECT newid FROM gym_mapping WHERE oldid=comments.gymid);
COMMIT;
ALTER TABLE gyms ENABLE TRIGGER USER;
ALTER TABLE user_gym_props ENABLE TRIGGER USER;
ALTER TABLE comments ENABLE TRIGGER USER;
DROP TABLE gym_mapping;