BEGIN;

 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/orGP_VBSXwgnXNKxE8n6U7eCmW3LM6RgNUXD1TJvMMmHFE4mDKlPpHqMJGvmda5mPm799vSgGybtn9Yrv1fxzQ' WHERE name='Ver Valley Walk 5';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/7oAn1qsEQHoSZD80I_TDKeNRy9Qy_X2PaLcsjtpjhW3Z4R5ZrkF9Z0B-dqbHeCl2pcP7rUdGXMgll5AiM47h' WHERE name='Pitch 4';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/JzIZbW_O_9gjSArV6_LPpm5bJetRfEr6FmtB7VFStILsYoKYHNhW-eb_DswGNIAGGhaap_HP-M_E2F5PlUE' WHERE name='Bernard''s Heath';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/PTKcprtdlFaH044vokyWHrRIj-YWNHfs7TxyeyrODxBwQclH55mCkcFETSsENlKPCji5oVe7xEjYOQtJcaI_' WHERE name='The Ancient Briton';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='St Luke''s Church Brickett Wood';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Bricket Wood Railway Station';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Bricket Wood United Reformed Church';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Butterflies and Flowers Metal Artwork';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Brickett Wood Common Circular Walk Marker';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Flower Lady';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Cock O'' the North';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Gobions Wood Nature Reserve';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/VXAOqQk4Y0kkBHezTYhCBq3y9TY2nZGJc1gRwU3IIS6IcvteY4Ns26NN7b3AqGquHUAYGONzTRxjRpFVHKfc' WHERE name='St Luke''s Church Cell Barnes';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/i1Vn1bci2GOfZUVWX7UCcddkhYNnbqLDT6syb3-KTXIbl-suEGnMLTZoDWifScVar469R_-piarz96CGYxXg' WHERE name='Cunningham Hill Football Park North Entrance';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/FCevEbNRrwszCFypUE7y8Pznt8RsAKF-cO7OsA31W7hB0C5Uuv6MggKuuH-htL8bn1e2RRMVLa97oVq_ncMf' WHERE name='London Road Club';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/1wBIH_DnHDSKY9L0LGpEvVQJDLC130-UtG_rAjZ7hvuiqw1ZnuSROG14zi6sF3Pw-aUtos6tt24d_ePJtHU' WHERE name='St Albans AOG Church';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/EM9LQPg1kBwdQwq7O2kYTl_jORcpYUwYDmlXCdv8GAEe84S1L_oVIC2IJsCp2Zn806Ezfo7KfGich6hsCHcVxA' WHERE name='Cunningham Hub';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/qOhb623YOWr-Qb8Xxewhke_aIIHHcMf5kN4mPZEWxKdvQydteF0XDH6zhj1WgWJSyTSfjCd28QcsHt7aI0Q' WHERE name='Martin''s Post Office';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='The Cock';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Colney Heath F C and Social Club';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Colney Heath Village Hall';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Colney Heath Community Park';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Couple Sculpture';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Plough and Harrow';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Batford Springs Damp Woodland Sign';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Upper Lea Valley Group Meeting Point';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Harpenden Railway Station';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Water Tower Shakespeare Road';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Harpenden''s Ups And Downs';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Apple Tree Project';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='The National Willow Collection';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Salmon Run';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Rothampstead Skatepark';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Entrance to Rothamsted Park';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Rothampsted Park Wildflower Meadows';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Rothamstead Millstone';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='St Mary the Virgin';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Harpenden Hilda Lydekker War Memorial Stone';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Batford Sign and Jubilee Sculpture';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Harpenden Indoor Bowls Club';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Ellenbrook Fields Story Zone';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Hatfield Aerodrome Heritage Trail';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Apollo Court Fountain';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Art & Design Building';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Space-Time Portal';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Comet Racer G-ACSS';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Milestone at de Havilland Campus';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/bV8O2tAHfzD9LhGqvrN6WyrH3IK9jJoa4rSOum7dn_OpC8GOYxpvYDdlef8v5NzTaZaU1UW4v7cnJHi6e9OdL0-0Kk93iNB1ZSUR_nUO9Cl4z9zx' WHERE name='The Rat''s Castle';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/FnprqOitZN-UCfVGZQafKXG4dV2dsmXPK7Gha4Lg2YC38QLl8oDoZZb3f1QYAcRorpVTdxv86aYrHAaIA0Dg' WHERE name='The Midland Railway Arch';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/c0qY0jKFhMJzl4uFieCNyS-bP7-WpGdBVOXrI4CoJ9zWTFnvgX6aFsCaSXshBFvTO2umjprO9RkoY2fZji8' WHERE name='Victoria''s Cannon';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/zwxN9ZiVhJ91Z_oNxdgES3_NlMzRlqi2UfLntzKZQzfdgjYdc202eDub_Qc6Jnac2D9dvrR6ADo0dZ8ky_kh' WHERE name='Fountain in Clarence Park';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/4rlcaPHc5fPIsWxU8ulyk3Qp8bW9D9_ZrWEanVlOkFFFSazT1FrvgL6sUuw1wJcAmEirj8whljo3BeI9zSkk' WHERE name='Fleetville Post Office';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/3o8x88Cyof_39YdAnM5Q9mJ-b9JaLYb2axO31Uxnh9IB3rmGyyI0jNNvm0Zqb-DQV5q0Ui2La1iQd-al5NQ' WHERE name='Chapel of Peace';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/iKYG_73ZpWvzPKGQDcIx0RB-ooGvPuQOl3GmMaRF5YNtm-wnsm-tjcdwGXhNbkD1VjLLO5KXrGqc_ksoxgyW' WHERE name='St Paul''s Church';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/QMUErak9FkC_7aQg-pRwrvK_uGAtasfi8miDughuHya_Avl99VYQLOwYNyLBkU9BBS2V_8oKoDclqWVj2SUW' WHERE name='Clarence Park Bandstand';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/OudoHabb6Z3LcVSG1kGdIr7FbyVBgFVgpBD_UgNIjrraEZYwEajx6OYh_484cUeLa8PdEkInSRUfWkwbQnTO' WHERE name='St Albans Royal Mail Sorting Office';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/rgvrU_eIpItiJIuc9BoRIbOeyJJ53odWdufy8F6JU-K9HFzIM_1BMXzyM9vCmV2GM2Y2gKz5s9lKc2fiDilt' WHERE name='Highfield Park - Tyttenhanger';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/EYcjtUFPl1CXB_NQ3J_2ER4j_sa17iqhjKCUhR4XztbIzQZ0Js7_Kme9qnknE00XD_x0xWJBzNOqxNrqqi3P' WHERE name='Hill End Garden of Rest';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/FF3m3RlLHRmEk4XNffDJh6nqHY3nMLteFNCZDcJ6WbQCzfzA3ScjbA0jL7uWbzxZJ85_twHCHTE63qr7TEVO' WHERE name='City of St. Alban Marker';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/AVQGKUGjT83iniil-C6NDjibD6C5eyRjz7psusiMhRkUHYczVgwJLRuASE0PXKTY9rxyU_vLlbz3zH-YvF65' WHERE name='Wildlife Totem';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/hOXt727b1sAL3VfEtjQ1UmUgc9agRECpcEMvf9Icqa5wuuAASg0z2zltiI497ep5Kh8FwcdwIVZYwdNoU5LA' WHERE name='Cell Barnes Orchard';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/v3jssiLpcOt9KqK9FvZcn8NJCtFlfsNXw7u_uvoBN6OSlGaGZfgi3XoWqKbyMoB7aAZ-iPMwYiikbuM0hnk' WHERE name='Highfield Park Wooden Sculpture';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/megmyP4bwV9aN2ldvHOurUE_AlkW7AjNQiWbDNm95wzjF5syZdSK2SblHbmlOmnWCXoACN36UPt4MenFKqaKyA' WHERE name='Hill End Commemorative Garden';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/K4V5zlRVGHRXE83mHBfpQHma_dvGMcK6qL40sX_ubFi9FnLYo5j5UbT_ZMFgwCSy404yPEZcVM28vTXmdJc0Jg' WHERE name='Diamond Jubilee Torch';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/oH_S7fL0mOzVBNmeaAopz4cVtVpbmPcVdjCa42N8-CBeopWCosQKbMlU2cHWfhUKaQAY-cWYyLqux3Z66EKG1A' WHERE name='St. Albans Rugby Club';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/KeE07LpT8iSwqyGu-Mgd0OYa-AdErxhtThcg2KQiPbrh96FRMU9Hx45Y0LoPdJMgLgdcXy0JiLTBRi2ucP6Y' WHERE name='Nick Marshall Plaque';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/b33Zex4bSe2a490prXDYP7h6kz-XaEk6uWzWpz0PCTIt1px9ZDH4Mc4wZRQg8jKgNeJV5N9XVUs9rZwShl7j' WHERE name='Tyttenhanger Green Sign';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/AhMcGIeK5emZWRzPQVE7UHnA7bIveZGcPApwG0XYLOiW3LJLcR-UiO-_kHtXWq3dH5uXRpQ9g3yk6KdGvQU' WHERE name='The Plough';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/XcX70aIcag6qDmUI529XFo59N3XpwFgRx2EdJ82sJ637py7BV3y3bMFCqEpQHgRMRF5Ng3Cb1z7mP0tPv3O-sQ' WHERE name='Jersey Farm Play Area';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/qdX1dZuK0onJHaHnofHeDBFOCrJ5IRvEM9qDw4rdx1sH6VKwTXmGMnapOHTuRbm-rTnxH8344BMuCZesrZLc' WHERE name='Newgate Close Play Area I';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/1Ej4_OJjPWKexwUUDXa-dgENeCmP4m_Je0j6hbg1zRw590ZXKNMTGFsZc0tpKtjO2kCDelU3c2aF4yzz866F' WHERE name='St Albans Cycles';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/us78HglLOxi80_0R0iS_0IvN8qdP0YxrXPZCzHDLgComO_xH2uQvAmYO4p-PHTsFEgvmBZn9VQCYGELQmhJB' WHERE name='Birklands Park Sign';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/pPcFZLF9TZS501cWDZLi14yzux1G29pbNCqoETQ26L1KAClRo93oJFlaUIK7v_N_y1K67h2uVxKsBlh8mBZC' WHERE name='Willows Farm Falconry Sculpture';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/_niUf2FIkJqEo1Qrdn6kRk6ALYLlIBelbQ4Gtewg-u_qI_bFsJGQVLNjs9gElPMZhy44pyhiWbFnr-G52-uJ' WHERE name='In Fond Memory Of Leonard Laidlaw';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/pWG7DtnPAGTO789nVvplQXVQAmI027h7ahHNgVqgbgDHJYAQvRLV2ffSFnG4SX11FvFx3S9SvQWriB-HLs-Qvg' WHERE name='The Old Clock Tower at Napsbury Park';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/Gnr8HQ9TYngbY0aoqTT7Ji8ovhaPvm113CBjfsfH7usBfdPiYB5VsEs4q4K8MWTepdM7bBkuL54Aac0TkX0' WHERE name='Carving London Colney';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/4jkC-5NFK1YwByasD84tJFrexUBt-7uXc8dryEQdzg4HvMjDa1teHEcmcujIJpJRSTzZez7Fv1hEZ1aOLa6RTw' WHERE name='Pink Chicken';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/vOo0QvKeGCF8TXMZN6EIAbW25AS1xURLKcNKsxlSo8c4HkIfbZpDBn0jESwcrI6b1dOiiwF9U8Ia9fsBd06zZg' WHERE name='Honey Bunny';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/CqrStdx7rkaHuffCCWEhpdVDTzwOiehojpNwBDFtu5z8AeL9awBVNXnwOOm-b7O33zwazyraZXq-bAzLE8uc' WHERE name='Library - London Colney';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/rW3a88z_81rVzdgRtmC7kV4fgoKaatcL-oSQdIhBpz8_3VX3Uo2T9Zaqvdnj264tOuR69BpAUyg5lhtGESHUvw' WHERE name='The Golden Lion';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/N3BLOMPWjYL3QajhpIOUwXjeJFvF4HiMCYzJrGZFKcLCS9axO8XrYtHJfTYl75RnHGfFQeuXBgNu2SnOYFyb' WHERE name='Our Lady of Walsingham Catholic Church';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/6m9Jxo237Ns4lLzlRr8fgiBBkgltO9vjbarkAdMuOf0sQB-qhnP9_o8t9O2NLY3L5jTnycdsFtC6y9uOWAeZ' WHERE name='St Michael''s Manor';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/4Sh_cg5ZUJLUIhBhzJAkW5owOdwFwsb-_R4iZbG4TSaVAWd8H5GAFVWsLbXNMgPVIV7JYwoUqVflje38KdEOZw' WHERE name='Homewood Road United Reform Church';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/crHBMJa1fUXY7zzPokw5jYUj450ltWbFOs9L93n0AUTS7pe77B0wbVI02eeHCHRvhDFpjc7obeO1YwqDej0' WHERE name='Tree Art';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/D57bhqG9Goq4_V5u8XG59gf0BgDG-uIPzn9t7_WXwQinDz4hDRT3MfbsPHSYlCTl5ksDdjSI_rQKMEwyv-cO' WHERE name='Marshalswick Post Office';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/0fGWi_ugj6CO0u0vlGWuWwnw54l3nWDS2B2TGkThbSIOcs0X5WBiaONkp55OC4pjPF1wklLWMQsltJCdF4m_' WHERE name='Marshalswick Library, St Albans';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/vf_6b3N6_J5ukmhlLP2H_hexOVBkY8_WLOhBwcQ0qwrD3DZgdm8wWL4PQhYBSQw9Mjz8dsIB34IlFMDo4wWe' WHERE name='St Saviour''s Church';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='The Holly Bush';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='The Hope & Anchor';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/2SMHOAq4eLQwZs0I_EdUBE5TgDOD1xHo_7LLxdNqE4jOj1qzfiGV5J-k-FX7IE1zSW3Mkp7aJLI8lKBb43BY' WHERE name='St Albans North Town Marker';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/yeSA-ng_Tghb1wTPx90QhazJp12FqdhQ1XXvSVgEcEe_bydNgr93qGAtI1U7o8k7mxurodUZkX2r7_8FKtLuHw' WHERE name='Christ Church St Albans';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/mAnS-qTowqH5I6FnB3IaSoKGCRnaINF-MpmyyprtCbCWU_i5GWZuxoFUwXDDYa8m-qsuaitmOz4OfnhxBmsz' WHERE name='Toulmin Drive Fort';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Nomansland Common';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/mKxNLtBuSwo0-mqr7CF3Ft9xPFyH9XjaZOLBQPvqhzKhOhfj1W2yUhgF9txO0q5Q7o7QVxDJZP_7h8SP3ayn' WHERE name='Landmark Centre';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/vMdEeHxjMLgocqChmHqkO0xdm6_xUp6dueaVGUcNv1SQ-mNNNIzub8D1aesTiatPyj7IlNofipVpKdE0tXBysQ' WHERE name='Forest Town Church';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/8VZJchW1JhsIq7kRc2RkXaJC2Bxm2TXbvp_4kwd-AAMIPy02jPfnb2joLPNj6IVptk3zAeuMJJ7Y1V5454Pn' WHERE name='Oaklands College Clock';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/XtsEyRhRRg5dDrdzGH-vcG9Eo8zESasRT2FiSecybj2NKBzQuKEhBDXK6xTgaj2gWzEwbhug52D8zM8PpTA-' WHERE name='Selectaglaze Crest, Dieu Et Mon Droit';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/sgsSMgb7OPKCRRJ4B91SKKopXFPT-6RmcBWmlGu256kFVuTqzkYLt9OKJgkaXQvJTzTVAjx5e1UcL-HGoXY' WHERE name='Butterfly World Gates';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/hP88Uong1mcLEXK8g2EhHfBT8-ctKF_VrUorwuS4jc189IWJwigpSUe4NAK5IjnlU46Sj7KUpRN_9TbufS5a' WHERE name='War Memorial';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/9yUga4mvr23Nd7cKd3ygpEBvh-u_DtKQi-RZL2O5MGL9loN4gtcBT1sio0whKejAGpTcQLCADQGJZCZnK4Wf' WHERE name='Park Street Mainline Station';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/EzYgEoZ6c5zb8lF2oebnGMqI04Vp38Rld66IvOugvkHuwFMLosMwPhjvwgOwredWEPpDDxnbsDbnVTtorkeU' WHERE name='Hertfordshire Fisheries';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/X5vm_RyxK0AfoGWiinqPWJEwydJE2Gt0WxlayEQOExIP1dfSUbt3jHhORqrGoF2MyVcaWwYQcPDjP3ixThNx' WHERE name='How Wood Railway Station';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/eW7OLVB4_WRkKbzTVdN8zau_QgzzF30QIRezQvBIGYeTcYFCzKpcW623v2BXa3h1qPVMZBhnwm5yuJSCSy-imA' WHERE name='River Ver Fishing Bench';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/nCi5DHfBBMAzvX6p-4XuB__j92zzz2Syqnxa0rLLwd3-8_WbSPRZmi8TK1Ix8svYSs8jwqJZzYTmqYVAk9mh' WHERE name='How Wood Nature Trail';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/jq-018UeoFW-rjQAn-Kc5HCamSDxEY69ua-biif3_3qT83SGQYjSnQDMs7UgqqnoTvOVGKs7cMVqpjx3H2zN' WHERE name='Chiswell Green Post Office';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/0aX3gW-iYxTfbuM1xaZMFYMxOR04TlgCtICMmNoG5OL9kjM7e9Pl3cUlazdB_XrgigjcUgwHgVSlBMgcxt3qtA' WHERE name='Greenwood Park Community Centre';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/-X47-1dPu_kv9IvhrhNuqGStqbizwc-pKhQNancxwWaepkm6xlqD98xFq_alC_8xgj7jj-H94ldoPoy3Ex5QKw' WHERE name='Greenwood Park and Nature Trail';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/wbMsw-ELZd7NNqAFGJOiSSIj_oDRNLROkYvXJvK_3-XWHPXc4AyEK1PnUM-Pf7HGIML1l9PaA2NQahAwq9cm' WHERE name='St Albans South Town Marker';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='St Mary''s Church, Redbourne';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Redbourne Watermill';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Redbourne Library';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Football Park Redbourn';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Brooke End Play Area';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='The Cricketers of Redbourn Public House';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='River Ver Trail Marker 1';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/oZfVEOEv4O2-h-ylbADYi4SsLYPhMhlNo5bbmKN7tu6BDK7kYWr1R-0Mv6FWvobKGwMSwh9MUY7OzZvHDP-C' WHERE name='St Leonards Church';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/JAoes0h-yuirHzFfzER_QYmkrUq2-U8STASpvhBJHp71-G7TOhA0RZkk6m6cShXicHMNRhDf1WlZ2RP08b8' WHERE name='Jersey Farm Woodland Park';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/0X7dDDuCWEwIrJ43JBAqoUZ-0l-FDqcIk-tt9la_gkvhpsWfvl-Nq4ouWBsC8epWjR7IItOmWVFiMzq0gdU' WHERE name='George Marten''s Cross';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/Yk4xTYlRfv1oOs8-LvLigpEvrauQWlQfTnDvyrov442wayHhnULLfmqWHxtpIFYFzUxHsV2dgR9TxO-hYfA' WHERE name='Sandridge Centenary of Parish Councils Plaque';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/jEzJ1t1rhJwFg9DC8jGhVbPOtoaQa1UG-12Wmlpc1SEttkw7K58ANh64Q18LJ8CnhzuZzV2XZlhSmYq1G1g' WHERE name='Sopwell Green Space';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/PZ6IR9GQbuz-yTUfC0iMpNrSjBwaY5XiX0ZtGi07Oyla-qUK_0LMJ6K7wXzi890_PfwLAs3yzW3Cqc_CcVA' WHERE name='Watercress Nature Reserve';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/CV9PExLjOcLWaYLLWKcqHzmC6YqDnIFoVALLsy3QKpvmDhLg1KIgCS2RqJGWzeUR_T3AE5XMGQP-XF7sQJfJDg' WHERE name='Sopwell House';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/Gk2JSMmyJnSOsAIb4DYpdrVIwBUONhgFLN8WNS4KYqENkIeMthRIsez1Marv--4Z6W1FWeIHlwUj6_t9PueL' WHERE name='St Julian Church';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/AucMaS8CqhXq5U6kIzk8X3T_I-wTvapmp0KMHwtA4t167IpF7saU1T8LlqdnjPubVsMf0PkA8sTtYCtdU-0bQw' WHERE name='Morton House';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/3bh0NOmK4h7u04hzdICPt2EC0f2xLmXOwxl7g1rWSfpImFy7PlrDktA6bgrL3f4m68vN-EsqmORxhtuQebAI' WHERE name='The Mermaid';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/kpvW2Q3a5erGid5U6_FMDS7SZ9UFS8KVvnUViAiezbZdZbZLN49eFV6BOhhFIQqBJ3T4Mc_Muow7SorQsGW5' WHERE name='Three Kings';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/xFrkvPZS0e_AH6f5dfO9MYu9bOWiXHXTwxVL1lyWER3w5db59fo_1UkXKls6ce7FkkI9qGbNCKKIHbAVqgCS4hlNPwlv6JrWvO5vVwDfNOLVGq_weQ' WHERE name='Saint Peter''s Anglican Church';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/ztJjJJ_zYowsJ5rre7FU4bVIOiHkCwnsd6nRU8c3xol2Xd8MxXvg9I1tD0tzwntkipOObrLcKY-4ci_TaFgA1Q' WHERE name='Religious Society of Friends (Quakers)';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/baMFdQib5z2iYnX0tTVRuKSJ2jCOVo5gQGwVi7jdrB2DxEW20tTnShaAqwmZLejSuDKdhewSR-lMx5Lm8g' WHERE name='SS Alban and Stephen Catholic Church';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/fvpa6b3MavShWXds1H6NxURUEUpr3Bx3o2GR_UiZw_8uJQqX1OIYkVVfdVMU6_gLi6R1cps-pLtOd5co_OCM' WHERE name='Victoria Pub';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/7e9g_spf5u1PYCD-wvxtlqouomym5kfWVBY4FMWAK4v9N5GEnVFG-fEs7COXG4G6kNL1lbkG6q8eShxyg8Ih' WHERE name='The Old Hat Factory St. Albans';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/W2-c3HsbYRO6xpZQAA7s687FlszKdSpG2hidfwYwJnoLP_XCi5AYqP-aCOOTh8pIiBLBKv7QohKWWiqrTBM' WHERE name='Jesus Cross at St Saviours';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/ho671gtzAxxirItnGcO7gfhxG_lHG_R7TaqIpDPpnyjENDl6sU_plhxM4j1jHWZtUtZHHbD9lNakVa--ePNOhw' WHERE name='Bleak House';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/RImdjm4YEHKA24p54mLiXTTKSINAjxRPTPYXbqaTvo-pEyFQFLKOa7IN5tXfkP3bnOQkyI1aSUUZKAuhEGA' WHERE name='St Albans Town Hall';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/HPE4NU1tEb21qjl72NteTvOBjP2jZP0gMBAD_ypRiFLGzWWz4slXErFbhN6nnw-Eb2dvbxoonV0x2QVhD3CXIg' WHERE name='St.Albans Civic Society Award 1988';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/hz2RN0eLDtMpQ6Jb5LN62xCcZWH3_AFsTstn7vsroBSB7wBEyPqdnrutqIIJTlA2DZzUYNaAzkY51zyR7oA' WHERE name='Abbey Theatre';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/D5XVDlOk8WYIzq4xefmPBrwtMt-9XfqG1JbOE3y-XtwJoL4cqbAOcVyBs1UrS4P1kVlxQ_kvN8G0Zgmkq_k' WHERE name='Centurion''s Statue';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/KdLDNb4jh-NHWXWzz6e-Nh5ou6FqE3T_rHRjiU2njg8Vi56du09NSttJj42wn_fc4xMhvb-jxKewle07Qdju' WHERE name='Saint Stephens Church';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/3SjbqCWPd9zk9KnvEvebJUqJaXfq85eY2H_x5TfaNvcqysZHnMnbUSnRuDDQVCecAKpNdDWh6UaqL9GPJgXw' WHERE name='St.Stephens Hill Pond';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/UvNRoHFe2QOXMCmZXzdrMUUcZUUOm9pfC3GEG7ILX1K04nyTYECEEes2NctOxjqqUM-UEg8Co4Vaq94gPx8f' WHERE name='The Castle Inn';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/keJ3TjZ4GdJFS6EhAmT1VcIt_Mk5BNjFDU-uYsbKhRLPGSOPdvWnTyeUQCRyHBWcTBIqoRZG3-sOrR-roHI' WHERE name='St Albans West Town Marker';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/agFI1FXV1RONnqxJmfCW4b3-h5ZTM-01X6bLDl3HZ6qzyhHEnr6CS8GJw2XzXudTPKsNjnPeZS7xUoGQ_Oiq' WHERE name='The London Gate and Roman Wall';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/AsWG-dvhOSTA5BNtgeVXW_oGWNErpkkzhNojx935n8VxqsyNA-F9dkAfjNahmQmFa5efIfrcRi7Q_tUFquQ' WHERE name='Roman City Defence Wall';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/p-qqBZ7Ngo2kquKtqO1LShcE_d0rGI74OnvgMFkSU8gtPVLVNP8q4sVexH6uvL1ixIgFYMAu1vnGbNVd9T1B' WHERE name='Romeland House';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/Z2yO2Wr9Pv_MsHzKlQ2Y2Y0PW6QaRS31uoBwohwACy26Fa60Gxbg38HZ0zGcTZk5w8Zkcar0nE-iPimGpwJU' WHERE name='The Boot Inn';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/qXcEWOYIb35_ye57mlpLgqU2JNflPqCkl_NLaYHZVHW0d9LU_Y8H_et7e6LhjGoQ_-gWrgMBJ7zA_F2dSST43g' WHERE name='Verulamium Park Entrance Map';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/KsNINJQ1H5kOCA9p2UGH0t2m5PFTFlStIrAohiJ9muHPAZ-VoutMVeT1G_o3B0Y2B3sXD46wYRCGFoRd9l1K_JM9-MyfOHMUxTwD4JAzvTeYHeA' WHERE name='Ye Olde Fighting Cocks';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/7HFN8iJSvQAqTf-om9KUuJZazheUN0ctVeH1V9X5moXElV1nx_CSEtXwknMhQEx-CUQDF65fKfTGa6YWlbmANQ' WHERE name='The Rose and Crown';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/Ni6TuLpgArW42KwTs_aWADwtVtw55emukw-u_fVwpVIkFL0iMVuktM0omkpXsM_biv-Rn_M656Yc2zshN7qk' WHERE name='Six Bells Public House';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/7Nrslko70c6IMtRLykK5sbEdxTmoGrJHXsL7sAO_R17oLRkr03NTOTVvgDN9sGYTDaDnKtQgAQKPYOEuHrIj7g' WHERE name='Roman Mosaic';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/W6zWNU99dkcfYlNRJDtTI8rvSpGduyayo1pN3TSafkqBG4lCle_8UsPHqwy1rQweMSGEu8QWokoJ7PnFZ4w' WHERE name='Roman Theatre of Verulamium';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/m_qbr7S3mvbffODTKmucsFM4cJ0xcGGRxwDB_UvACcqMlEthAejLa-PmwO5NBQHMA_QfoSdbzQPKK2l3b3o' WHERE name='Entrance to Roman Theatre of Verulamium';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Gorhambury';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Melissa Field 1933';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='St Thomas More Roman Catholic Church';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Wheathampstead Sign';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Wheathampstead Cricket Club';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='John Bunyan''s Chimney';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Devil''s Dyke';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Wheathampstead Methodist Chapel';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Hilldyke Road Play Area';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/1oZh8kDbsidzsSE6nGMa_cYk6gW1SiXnnbQFnw0s7D-jfs89YZihIL4yVcvu0l4yQhm95GhbDV00ELmA1Tv2' WHERE name='Verulamium Park South Entrance';
 UPDATE gyms SET image_url='https://lh4.ggpht.com/Fddl5mlchKhKnyx0XPo4GBDDtvFdfybdlUx-8evVJyjPL0Ai9d2wPzd2T84XEG9SmXeJqS9ds8NsbfN2v9LQ' WHERE name='N&C Entrance';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/wiiQf17A3jhZKqNBDXnhd9BXWCFiki6S8ZLyXYfVaB7h58wCYh-MFW6dPlj7NhNSyHb-3EEOjjYXrwUmGTT5Jw' WHERE name='Gardens Of The Rose';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Harpenden Lydekker Park';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/EqGmitE_2sScJXCC3OaCe-4Al4x1r-GKgcw6k3s1DK5c11uKq4RFSKZZMI5ZYbOLQEcNeQoLVoX5Xe_IPj-cqw' WHERE name='Verdi''s';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/IWv_fTdzeDM0EZQj3JO8e8oNiDhG0PJ5knoJ_N4E4MiYSSf8ZjGAL1oIdQGjrf56vMvdahwa29z7orCGb60i' WHERE name='The Cathedral & Abbey Church of Saint Alban';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Cumberland Gardens';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/_rVI8IYKPq7slaShhU-7OT865ceHwBA2QXP0j2YAHgVVFAXnfX1R9KgcedrlocNfJlRVD8iUaw4hsy0XV5I' WHERE name='Batchwood Turret';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/S6apICZw8B19Jlv6ypc1sFXW2kdmyRmsq5xVUyfLV92c-qYDLN0ln_8GOTDK-2p_Njdx7T_w7cDUFd6W3lTlDg' WHERE name='God is with us';
 UPDATE gyms SET image_url='https://lh3.googleusercontent.com/YEu2IG8QQB5Ch1Ni46tUIOz4vKHZgWYL5Xk5Ve5T3thOeYD653lKiI5gko3o_53mMHoJuRrZsAny6PjUy4CH' WHERE name='Verulam Consultants';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/ZmfXlQcaQod9Xq0JkK6f0qjtEYpaOr6HYjM8BwHYtB6GDwdN5r6YZP4XPCnivMjUlbHRK4fEtYjSCPqochRMPA' WHERE name='Sopwell Nunnery';
 UPDATE gyms SET image_url='https://lh6.ggpht.com/8n_VTWU_fHsp6rNBZoKzjUBhhYQedj3tHkDLkENhi-_IeXLNVbw6oG4tT4GMU_7aTC3NTp0v7vrpnPkPPaq8Kg' WHERE name='Sopwell Nunnery Green Space';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/Hg4kEY-swNauP91f-y-kVqmtABnmt0mf_BqScHxW9OFxChkRNByfYaoas25cqkTVWWWHXWNQ0OtUtNJxdKCT' WHERE name='Leoro Gallery';
 UPDATE gyms SET image_url='https://lh5.ggpht.com/imjawXersDjHZ0jf45Dws44QUBWjkD1oMjG1xiD6sC3BzjL79h3p-vVYnEl_pkGwmHhVeirO7eonFVCeNcSfQg' WHERE name='Sopwell Gate Lodge';
 UPDATE gyms SET image_url='https://lh3.ggpht.com/8lmfckU6Z7y9nLZc8jcZ0kVfYqsHi8E7VpVKGzivvoSk29TB5IfrdP9wYoiLQxiZBoEMVq56G0MMpDFsYZji' WHERE name='Blackberry Arch';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Nomansland Model Aircraft Landing Strip';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Bowers Parade Sensory Garden';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Woodland Cycle Path';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Welcome To The Magical Wood Wooden Marker';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Discover an amazing magic carpet';
 UPDATE gyms SET image_url='https://www.gymbadger.com/images/badger.png' WHERE name='Brickett Wood Common 2';

COMMIT;