BEGIN;

insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Absol', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Aggron', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Alakazam', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Articuno', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Celebi', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Charmeleon', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Cloyster', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Entei', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Gengar', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Golem', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Groudon', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Ho-Oh', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Ivysaur', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Kyogre', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Lapras', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Lugia', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Machamp', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Magikarp', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Magneton', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Marowak', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Mawile', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Metapod', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Mew', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Mewtwo', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Moltres', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Nidoking', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Nidoqueen', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Ninetales', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Omastar', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Poliwrath', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Porygon', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Raikou', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Sableye', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Sandslash', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Scyther', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Snorlax', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Suicune', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Tentacruel', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Tyranitar', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Victreebel', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Wailmer', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Wartortle', true);
insert into pokemon (id, name, raidboss) values (nextval('pokemonids'), 'Zapdos', true);

COMMIT;