begin;
alter table gyms add short_name varchar(100);
update gyms set short_name='Abbey Theatre' where name='Abbey Theatre';
update gyms set short_name='Apollo Court Fountain' where name='Apollo Court Fountain';
update gyms set short_name='Apple Tree Project' where name='Apple Tree Project';
update gyms set short_name='Art & Design Building' where name='Art & Design Building';
update gyms set short_name='Batchwood Turret' where name='Batchwood Turret';
update gyms set short_name='Batford Sign and Jubilee Sculpture' where name='Batford Sign and Jubilee Sculpture';
update gyms set short_name='Batford Springs Damp Woodland Sign' where name='Batford Springs Damp Woodland Sign';
update gyms set short_name='Bernard''s Heath' where name='Bernard''s Heath';
update gyms set short_name='Birklands Park Sign' where name='Birklands Park Sign';
update gyms set short_name='Blackberry Arch' where name='Blackberry Arch';
update gyms set short_name='Bleak House' where name='Bleak House';
update gyms set short_name='Bowers Parade Sensory Garden' where name='Bowers Parade Sensory Garden';
update gyms set short_name='Bricket Wood Railway Station' where name='Bricket Wood Railway Station';
update gyms set short_name='Bricket Wood United Reformed Church' where name='Bricket Wood United Reformed Church';
update gyms set short_name='Brickett Wood Common 2' where name='Brickett Wood Common 2';
update gyms set short_name='Brickett Wood Common Circular Walk Marker' where name='Brickett Wood Common Circular Walk Marker';
update gyms set short_name='Brooke End Play Area' where name='Brooke End Play Area';
update gyms set short_name='Butterflies and Flowers Metal Artwork' where name='Butterflies and Flowers Metal Artwork';
update gyms set short_name='Butterfly World Gates' where name='Butterfly World Gates';
update gyms set short_name='Carving London Colney' where name='Carving London Colney';
update gyms set short_name='Cell Barnes Orchard' where name='Cell Barnes Orchard';
update gyms set short_name='Centurion''s Statue' where name='Centurion''s Statue';
update gyms set short_name='Chapel of Peace' where name='Chapel of Peace';
update gyms set short_name='Chiswell Green Post Office' where name='Chiswell Green Post Office';
update gyms set short_name='Christ Church St Albans' where name='Christ Church St Albans';
update gyms set short_name='City of St. Alban Marker' where name='City of St. Alban Marker';
update gyms set short_name='Clarence Park Bandstand' where name='Clarence Park Bandstand';
update gyms set short_name='Cock O'' the North' where name='Cock O'' the North';
update gyms set short_name='Colney Heath Community Park' where name='Colney Heath Community Park';
update gyms set short_name='Colney Heath F C and Social Club' where name='Colney Heath F C and Social Club';
update gyms set short_name='Colney Heath Village Hall' where name='Colney Heath Village Hall';
update gyms set short_name='Comet Racer G-ACSS' where name='Comet Racer G-ACSS';
update gyms set short_name='Couple Sculpture' where name='Couple Sculpture';
update gyms set short_name='Cumberland Gardens' where name='Cumberland Gardens';
update gyms set short_name='Cunningham Hill Football Park' where name='Cunningham Hill Football Park North Entrance';
update gyms set short_name='Cunningham Hub' where name='Cunningham Hub';
update gyms set short_name='Devil''s Dyke' where name='Devil''s Dyke';
update gyms set short_name='Diamond Jubilee Torch' where name='Diamond Jubilee Torch';
update gyms set short_name='Discover an amazing magic carpet' where name='Discover an amazing magic carpet';
update gyms set short_name='Disney Arch' where name='Disney Arch';
update gyms set short_name='Ellenbrook Fields Story Zone' where name='Ellenbrook Fields Story Zone';
update gyms set short_name='Entrance to Roman Theatre' where name='Entrance to Roman Theatre of Verulamium';
update gyms set short_name='Entrance to Rothamsted Park' where name='Entrance to Rothamsted Park';
update gyms set short_name='Fleetville Post Office' where name='Fleetville Post Office';
update gyms set short_name='Flower Lady' where name='Flower Lady';
update gyms set short_name='Football Park Redbourn' where name='Football Park Redbourn';
update gyms set short_name='Forest Town Church' where name='Forest Town Church';
update gyms set short_name='Fountain in Clarence Park' where name='Fountain in Clarence Park';
update gyms set short_name='Gardens Of The Rose' where name='Gardens Of The Rose';
update gyms set short_name='George Marten''s Cross' where name='George Marten''s Cross';
update gyms set short_name='Gobions Wood Nature Reserve' where name='Gobions Wood Nature Reserve';
update gyms set short_name='God is with us' where name='God is with us';
update gyms set short_name='Gorhambury' where name='Gorhambury';
update gyms set short_name='Greenwood Park Community' where name='Greenwood Park Community Centre';
update gyms set short_name='Greenwood Park and Nature Trail' where name='Greenwood Park and Nature Trail';
update gyms set short_name='Harpenden Hilda Lydekker War' where name='Harpenden Hilda Lydekker War Memorial Stone';
update gyms set short_name='Harpenden Indoor Bowls Club' where name='Harpenden Indoor Bowls Club';
update gyms set short_name='arpenden Lydekker Park' where name='Harpenden Lydekker Park';
update gyms set short_name='Harpenden Railway Station' where name='Harpenden Railway Station';
update gyms set short_name='Harpenden''s Ups And Downs' where name='Harpenden''s Ups And Downs';
update gyms set short_name='Hatfield Aerodrome' where name='Hatfield Aerodrome Heritage Trail';
update gyms set short_name='Heartwood Forest Map' where name='Heartwood Forest Map';
update gyms set short_name='Hertfordshire Fisheries' where name='Hertfordshire Fisheries';
update gyms set short_name='Highfield Park - Tyttenhanger' where name='Highfield Park - Tyttenhanger';
update gyms set short_name='Highfield Park Wooden' where name='Highfield Park Wooden Sculpture';
update gyms set short_name='Hill End Commemorative' where name='Hill End Commemorative Garden';
update gyms set short_name='Hill End Garden of Rest' where name='Hill End Garden of Rest';
update gyms set short_name='Hilldyke Road Play Area' where name='Hilldyke Road Play Area';
update gyms set short_name='Homewood Road United Reform' where name='Homewood Road United Reform Church';
update gyms set short_name='Honey Bunny' where name='Honey Bunny';
update gyms set short_name='How Wood Nature Trail' where name='How Wood Nature Trail';
update gyms set short_name='How Wood Railway Station' where name='How Wood Railway Station';
update gyms set short_name='In Fond Memory Of Leonard Laidlaw' where name='In Fond Memory Of Leonard Laidlaw';
update gyms set short_name='Jersey Farm Play Area' where name='Jersey Farm Play Area';
update gyms set short_name='Jersey Farm Woodland Park' where name='Jersey Farm Woodland Park';
update gyms set short_name='Jesus Cross at St Saviours' where name='Jesus Cross at St Saviours';
update gyms set short_name='John Bunyan''s Chimney' where name='John Bunyan''s Chimney';
update gyms set short_name='Landmark Centre' where name='Landmark Centre';
update gyms set short_name='Leoro Gallery' where name='Leoro Gallery';
update gyms set short_name='Library - London Colney' where name='Library - London Colney';
update gyms set short_name='London Road Club' where name='London Road Club';
update gyms set short_name='Magical Meander - Frog' where name='Magical Meander - Frog';
update gyms set short_name='Marshalswick Library, St Albans' where name='Marshalswick Library, St Albans';
update gyms set short_name='Marshalswick Post Office' where name='Marshalswick Post Office';
update gyms set short_name='Martin''s Post Office' where name='Martin''s Post Office';
update gyms set short_name='Melissa Field 1933' where name='Melissa Field 1933';
update gyms set short_name='Milestone at de Havilland' where name='Milestone at de Havilland Campus';
update gyms set short_name='Morton House' where name='Morton House';
update gyms set short_name='N&C Entrance' where name='N&C Entrance';
update gyms set short_name='Newgate Close Play Area I' where name='Newgate Close Play Area I';
update gyms set short_name='Nick Marshall Plaque' where name='Nick Marshall Plaque';
update gyms set short_name='Nomansland Common' where name='Nomansland Common';
update gyms set short_name='Nomansland Model Aircraft Landing Strip' where name='Nomansland Model Aircraft Landing Strip';
update gyms set short_name='Oaklands College Clock' where name='Oaklands College Clock';
update gyms set short_name='Our Lady of Walsingham' where name='Our Lady of Walsingham Catholic Church';
update gyms set short_name='Park Street Mainline Station' where name='Park Street Mainline Station';
update gyms set short_name='Pink Chicken' where name='Pink Chicken';
update gyms set short_name='Pitch 4' where name='Pitch 4';
update gyms set short_name='Plough and Harrow' where name='Plough and Harrow';
update gyms set short_name='Redbourne Library' where name='Redbourne Library';
update gyms set short_name='Redbourne Watermill' where name='Redbourne Watermill';
update gyms set short_name='Religious Society of Friends' where name='Religious Society of Friends (Quakers)';
update gyms set short_name='River Ver Fishing Bench' where name='River Ver Fishing Bench';
update gyms set short_name='River Ver Trail Marker 1' where name='River Ver Trail Marker 1';
update gyms set short_name='Roman City Defence Wall' where name='Roman City Defence Wall';
update gyms set short_name='Roman Mosaic' where name='Roman Mosaic';
update gyms set short_name='Roman Theatre of Verulamium' where name='Roman Theatre of Verulamium';
update gyms set short_name='Romeland House' where name='Romeland House';
update gyms set short_name='Rothampstead Skatepark' where name='Rothampstead Skatepark';
update gyms set short_name='Rothampsted Park Wildflower Meadows' where name='Rothampsted Park Wildflower Meadows';
update gyms set short_name='Rothamstead Millstone' where name='Rothamstead Millstone';
update gyms set short_name='SS Alban and Stephen Catholic' where name='SS Alban and Stephen Catholic Church';
update gyms set short_name='Saint Peter''s Anglican Church' where name='Saint Peter''s Anglican Church';
update gyms set short_name='Saint Stephens Church' where name='Saint Stephens Church';
update gyms set short_name='Salmon Run' where name='Salmon Run';
update gyms set short_name='Sandridge Centenary of Parish Councils Plaque' where name='Sandridge Centenary of Parish Councils Plaque';
update gyms set short_name='Selectaglaze Crest, Dieu Et' where name='Selectaglaze Crest, Dieu Et Mon Droit';
update gyms set short_name='Six Bells Public House' where name='Six Bells Public House';
update gyms set short_name='Sopwell Gate Lodge' where name='Sopwell Gate Lodge';
update gyms set short_name='Sopwell Green Space' where name='Sopwell Green Space';
update gyms set short_name='Sopwell House' where name='Sopwell House';
update gyms set short_name='Sopwell Nunnery Green' where name='Sopwell Nunnery Green Space';
update gyms set short_name='Sopwell Nunnery' where name='Sopwell Nunnery';
update gyms set short_name='Space-Time Portal' where name='Space-Time Portal';
update gyms set short_name='St Albans AOG Church' where name='St Albans AOG Church';
update gyms set short_name='St Albans Cycles' where name='St Albans Cycles';
update gyms set short_name='St Albans North Town Marker' where name='St Albans North Town Marker';
update gyms set short_name='St Albans Royal Mail Sorting' where name='St Albans Royal Mail Sorting Office';
update gyms set short_name='St Albans South Town Marker' where name='St Albans South Town Marker';
update gyms set short_name='St Albans Town Hall' where name='St Albans Town Hall';
update gyms set short_name='St Albans West Town Marker' where name='St Albans West Town Marker';
update gyms set short_name='St Julian Church' where name='St Julian Church';
update gyms set short_name='St Leonards Church' where name='St Leonards Church';
update gyms set short_name='St Luke''s Church' where name='St Luke''s Church Brickett Wood';
update gyms set short_name='St Luke''s Church' where name='St Luke''s Church Cell Barnes';
update gyms set short_name='St Mary the Virgin' where name='St Mary the Virgin';
update gyms set short_name='St Mary''s Church,' where name='St Mary''s Church, Redbourne';
update gyms set short_name='St Michael''s Manor' where name='St Michael''s Manor';
update gyms set short_name='St Paul''s Church' where name='St Paul''s Church';
update gyms set short_name='St Saviour''s Church' where name='St Saviour''s Church';
update gyms set short_name='St Thomas More Roman Catholic Church' where name='St Thomas More Roman Catholic Church';
update gyms set short_name='St. Albans Rugby Club' where name='St. Albans Rugby Club';
update gyms set short_name='St.Albans Civic Society Award' where name='St.Albans Civic Society Award 1988';
update gyms set short_name='St.Stephens Hill Pond' where name='St.Stephens Hill Pond';
update gyms set short_name='The Ancient Briton' where name='The Ancient Briton';
update gyms set short_name='The Boot Inn' where name='The Boot Inn';
update gyms set short_name='The Castle Inn' where name='The Castle Inn';
update gyms set short_name='The Cathedral & Abbey Church of' where name='The Cathedral & Abbey Church of Saint Alban';
update gyms set short_name='The Cock' where name='The Cock';
update gyms set short_name='The Cricketers of Redbourn' where name='The Cricketers of Redbourn Public House';
update gyms set short_name='The Golden Lion' where name='The Golden Lion';
update gyms set short_name='The Holly Bush' where name='The Holly Bush';
update gyms set short_name='The Hope & Anchor' where name='The Hope & Anchor';
update gyms set short_name='The London Gate and Roman' where name='The London Gate and Roman Wall';
update gyms set short_name='The Mermaid' where name='The Mermaid';
update gyms set short_name='The Midland Railway Arch' where name='The Midland Railway Arch';
update gyms set short_name='The National Willow Collection' where name='The National Willow Collection';
update gyms set short_name='The Old Clock Tower at Napsbury Park' where name='The Old Clock Tower at Napsbury Park';
update gyms set short_name='The Old Hat Factory St.' where name='The Old Hat Factory St. Albans';
update gyms set short_name='The Plough' where name='The Plough';
update gyms set short_name='The Rat''s Castle' where name='The Rat''s Castle';
update gyms set short_name='The Rose and Crown' where name='The Rose and Crown';
update gyms set short_name='Three Kings' where name='Three Kings';
update gyms set short_name='Toulmin Drive Fort' where name='Toulmin Drive Fort';
update gyms set short_name='Tree Art' where name='Tree Art';
update gyms set short_name='Tyttenhanger Green Sign' where name='Tyttenhanger Green Sign';
update gyms set short_name='Upper Lea Valley Group Meeting Point' where name='Upper Lea Valley Group Meeting Point';
update gyms set short_name='Ver Valley Walk 5' where name='Ver Valley Walk 5';
update gyms set short_name='Verdi''s' where name='Verdi''s';
update gyms set short_name='Verulam Consultants' where name='Verulam Consultants';
update gyms set short_name='Verulamium Park Entrance' where name='Verulamium Park Entrance Map';
update gyms set short_name='Verulamium Park South' where name='Verulamium Park South Entrance';
update gyms set short_name='Victoria Pub' where name='Victoria Pub';
update gyms set short_name='Victoria''s Cannon' where name='Victoria''s Cannon';
update gyms set short_name='War Memorial' where name='War Memorial';
update gyms set short_name='Water Tower Shakespeare Road' where name='Water Tower Shakespeare Road';
update gyms set short_name='Watercress Nature Reserve' where name='Watercress Nature Reserve';
update gyms set short_name='Welcome To The Magical Wood Wooden Marker' where name='Welcome To The Magical Wood Wooden Marker';
update gyms set short_name='Wheathampstead Cricket Club' where name='Wheathampstead Cricket Club';
update gyms set short_name='Wheathampstead Methodist' where name='Wheathampstead Methodist Chapel';
update gyms set short_name='Wheathampstead Sign' where name='Wheathampstead Sign';
update gyms set short_name='Wildlife Totem' where name='Wildlife Totem';
update gyms set short_name='Willows Farm Falconry Sculpture' where name='Willows Farm Falconry Sculpture';
update gyms set short_name='Woodland Cycle Path' where name='Woodland Cycle Path';
update gyms set short_name='Ye Olde Fighting Cocks' where name='Ye Olde Fighting Cocks';
commit;
